// <auto-generated />
using System;
using LdapSync.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LdapSync.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int?>("GidNumber")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrganizativa")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectClass")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("DistinguishedName")
                        .IsUnique()
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 512 });

                    b.HasIndex("GidNumber");

                    b.HasIndex("IsActive");

                    b.ToTable("LdapGroups");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapServer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("BaseDn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("BindDn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("BindPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("GroupSearchFilter")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastConnectionTest")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ServerType")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseTls")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserSearchFilter")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("ValidateCertificate")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("LdapServers");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("AccountLockoutExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("GidNumber")
                        .HasColumnType("int");

                    b.Property<string>("HomeDirectory")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsAccountLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("LoginShell")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Organization")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Ou")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("PasswordHistoryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PasswordLastChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PasswordMaxAgeDays")
                        .HasColumnType("int");

                    b.Property<int?>("PasswordMinAgeDays")
                        .HasColumnType("int");

                    b.Property<int?>("PasswordWarningDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("UidNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 255 });

                    b.HasIndex("DistinguishedName")
                        .IsUnique()
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 512 });

                    b.HasIndex("Email");

                    b.HasIndex("GidNumber");

                    b.HasIndex("IsActive");

                    b.HasIndex("Uid");

                    b.ToTable("LdapUsers");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.SyncConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CronSchedule")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("DeactivateOrphanUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DeleteOrphanGroups")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ExcludedAttributes")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int?>("ForcePasswordResetDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("MaxEntries")
                        .HasColumnType("int");

                    b.Property<int>("PageSize")
                        .HasColumnType("int");

                    b.Property<string>("SearchBase")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("SyncGroups")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SyncMemberships")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SyncMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("SyncPasswordPolicies")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SyncPasswords")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SyncUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("SyncConfigurations");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.SyncLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("int");

                    b.Property<int>("GroupsProcessed")
                        .HasColumnType("int");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MembershipsProcessed")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsersProcessed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.UserGroupMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("MemberAttributeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.SyncConfiguration", b =>
                {
                    b.HasOne("LdapSync.Domain.Entities.LdapServer", "Server")
                        .WithOne("SyncConfiguration")
                        .HasForeignKey("LdapSync.Domain.Entities.SyncConfiguration", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.UserGroupMembership", b =>
                {
                    b.HasOne("LdapSync.Domain.Entities.LdapGroup", "Group")
                        .WithMany("UserMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LdapSync.Domain.Entities.LdapUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapGroup", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapServer", b =>
                {
                    b.Navigation("SyncConfiguration");
                });

            modelBuilder.Entity("LdapSync.Domain.Entities.LdapUser", b =>
                {
                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
